# Generated by Django 5.2.8 on 2025-11-25 12:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Recurring payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('interval', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Billing interval', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current subscription status', max_length=20)),
                ('next_payment_date', models.DateTimeField(help_text='Date when next payment is due')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when subscription started')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (ISO 4217)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Current payment status', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Unique transaction ID from payment gateway', max_length=100, null=True, unique=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time when payment was processed', null=True)),
                ('customer_email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('subscription', models.ForeignKey(blank=True, help_text='Associated subscription for recurring payments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='command.subscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
